export const POSITIONS = {
  Hulk: {
    cameraPositionZ: -12,
    cameraPositionY: 5,
    primitive: [0, 3, 0],
    meshPosition: [0, -1, 0],
    intensity: 0,
    scale: [1, 1, 1],
  },
  Thor: {
    cameraPositionZ: -2,
    cameraPositionY: 0,
    primitive: [0, 0, 0],
    meshPosition: [0, -1, 0],
    intensity: 0,
    scale: [1, 1, 1],
  },
  SpiderMan: {
    cameraPositionZ: -2,
    cameraPositionY: 0,
    primitive: [0, 0, 0],
    meshPosition: [0, -1, 0],
    intensity: 0,
    scale: [1, 1, 1],
  },
  Nebula: {
    cameraPositionZ: 1,
    cameraPositionY: 0,
    primitive: [0, -0.5, 0],
    meshPosition: [0, 0, 0],
    intensity: 0,
    scale: [1, 1, 1],
  },
  Groot: {
    cameraPositionZ: -100,
    cameraPositionY: 0,
    primitive: [0, -40, 0],
    meshPosition: [0, -40, 10],
    intensity: 0,
    scale: [0.1, 0.1, 0.1],
  },
  IronMan: {
    cameraPositionZ: -0.9,
    cameraPositionY: 0.3,
    primitive: [0, 0.5, 0],
    meshPosition: [0, -1, 0],
    intensity: 0,
    scale: [1, 1, 1],
  },
  CaptainAmerica: {
    cameraPositionZ: -2.5,
    cameraPositionY: 0.7,
    primitive: [0, 0, 0],
    meshPosition: [0, -1.75, 0],
    intensity: 1.4,
    scale: [1, 1, 1],
  },
  BlackPanther: {
    cameraPositionZ: -1.5,
    cameraPositionY: 0.5,
    primitive: [0, 0, 0],
    meshPosition: [0, -0.7, 0],
    scale: [0.009, 0.009, 0.009],
    intensity: 2.4,
  },
  Thanos: {
    cameraPositionZ: -1,
    cameraPositionY: 0.4,
    primitive: [0, 0, 0],
    meshPosition: [0, -0.6, 0],
    intensity: 0,
    scale: [0.01, 0.01, 0.01],
  },
};
